config/routes.rb
Rails.application.routes.draw do
  root "players#index"

  get '/matches', to: 'matches#index'

  resources :players
  resources :matches

  get '/generate_matches', to: 'players#generate_matches'
  post '/matches_to_play', to: 'players#matches_to_play'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/match.rb
class WinnerLooserUniqueness < ActiveModel::Validator
  def validate(record)
    if record.winning_player_id == record.losing_player_id
      record.errors.add :winning_player_id, "and Loosing player cannot be the same"
    end
  end
end

class Match < ApplicationRecord
  validates :winning_player_id, :losing_player_id, :winner_score, :loser_score, presence: true
  validates_with WinnerLooserUniqueness

  def winner
    Player.find(winning_player_id)
  end

  def loser
    Player.find(losing_player_id)
  end
end

app/models/player.rb
class PokemonExists < ActiveModel::Validator
  def validate(record)
    if "Not Found" == HTTParty.get("https://pokeapi.co/api/v2/pokemon/#{record.favorite_pokemon}").body
      record.errors.add :favorite_pokemon, "does not exist!"
    end
  end
end

class Player < ApplicationRecord
  validates :name, :favorite_pokemon, :favorite_pokemon_id, presence: true
  validates :name, uniqueness: true
  validates_with PokemonExists

  def find_by_name(name)
    Player.where(name: name)
  end

  def matches
    Match.where((["winning_player_id = ? or losing_player_id = ?", "#{id}", "#{id}"]))
  end
  def wins_and_losses
    @wins_and_losses ||= build_wins_and_losses_hash
  end
  def build_wins_and_losses_hash
    wins_and_losses_hash = {
      matches_won: 0,
      matches_lost: 0,
      games_won: 0,
      games_lost: 0,
    }
    matches.each do |match|
      if match.winning_player_id == id
        wins_and_losses_hash[:matches_won] += 1
        wins_and_losses_hash[:games_won] += match.winner_score
        wins_and_losses_hash[:games_lost] += match.loser_score
      else
        wins_and_losses_hash[:matches_lost] += 1
        wins_and_losses_hash[:games_won] += match.loser_score
        wins_and_losses_hash[:games_lost] += match.winner_score
      end
    end
    wins_and_losses_hash
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def index
    @matches = Match.all
  end
  def new
    @match = Match.new
  end

  def create
    @match = Match.new(match_params)

    if @match.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @match = Match.find(params[:id])
  end

  def update
    @match = Match.find(params[:id])

    if @match.update(match_params)
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
  def match_params
    params.require(:match).permit(:winning_player_id, :losing_player_id, :winner_score, :loser_score)
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    players = Player.all
    @sorted_players = players.to_a.sort_by { |player| player.wins_and_losses[:matches_won] }.reverse!
  end

  def show
    @player = Player.find(params[:id])
  end

  def new
    @player = Player.new
  end

  def create
    player_params['favorite_pokemon'].downcase!
    fave_pokemon = player_params['favorite_pokemon']
    new_params = player_params.merge!({'favorite_pokemon_id' => get_pokemon_id(fave_pokemon)})
    @player = Player.new(new_params)

    if @player.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @player = Player.find(params[:id])
  end

  def update
    player_params['favorite_pokemon'].downcase!
    fave_pokemon = player_params['favorite_pokemon']
    new_params = player_params.merge!({'favorite_pokemon_id' => get_pokemon_id(fave_pokemon)})
    @player = Player.find(params[:id])

    if @player.update(new_params)
      redirect_to @player
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def generate_matches
    @players = Player.all
  end

  def matches_to_play
    players = player_params[:selected]
    players_array = []
    players.each do |player|
      if player[1] == '1'
        players_array.push(Player.find_by_name(player[0]))
      end
    end
    @pairings = build_pairs(players_array)
  end

  private

  def build_pairs(players)
    pairs = {}
    players.shuffle!
    while !players.empty?
      if players.length > 1
        pairs[players.pop] = players.pop
      else
        pairs[players.pop] = 'Bye'
      end
    end
    pairs
  end

  def get_pokemon_id(fave_pokemon)
    response = HTTParty.get("https://pokeapi.co/api/v2/pokemon/#{fave_pokemon}")

    if "Not Found" == response.body
      1
    else
      response['id']
    end
  end

  def player_params
    params.require(:player).permit(:name, :favorite_pokemon, selected: {})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar bg-light">
  <form class="container-fluid justify-content-start">
    <%= image_tag("pokeball.png", height: 30, width: 30) %>
    <%= link_to "Home", root_path, class: "btn btn-light ms-2" %>
    <%= link_to "New Player", new_player_path, class: "btn btn-light ms-2" %>
    <%= link_to "Record Match", new_match_path, class: "btn btn-light ms-2" %>
    <%= link_to "Generate Matches", "/generate_matches", class: "btn btn-light ms-2" %>
  </form>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokemon League</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('pokeball.png') %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="container mt-3">
      <%= yield %>
    </div>
  </body>
</html>

app/views/matches/_form.html.erb
<%= form_with model: @match do |form| %>
  <% @match.errors.full_messages_for(:winning_player_id).each do |message| %>
    <div class="row mb-3 justify-content-center">
      <div class="alert alert-danger col-sm-7"><%= message %></div>
    </div>
  <% end %>
  <div class="row mb-3 justify-content-center">
    <%= form.label :winner, class: "col-sm-2 col-form-label" %><br>
    <div class="col-sm-5">
      <%= form.collection_select :winning_player_id, Player.order(:name),:id,:name, { include_blank: true }, { class: "form-select" } %>
    </div>
  </div>

  <div class="row mb-3 justify-content-center">
    <%= form.label :loser, class: "col-sm-2 col-form-label" %><br>
    <div class="col-sm-5">
      <%= form.collection_select :losing_player_id, Player.order(:name),:id,:name, { include_blank: true }, { class: "form-select" } %>
    </div>
  </div>

  <div class="row mb-3 justify-content-center">
    <%= form.label :winner_score, class: "col-sm-2 col-form-label" %><br>
    <div class="col-sm-5">
      <%= form.number_field :winner_score, class: "form-control" %>
    </div>
  </div>

  <div class="row mb-3 justify-content-center">
    <%= form.label :loser_score, class: "col-sm-2 col-form-label" %><br>
    <div class="col-sm-5">
      <%= form.number_field :loser_score, class: "form-control" %>
    </div>
  </div>

  <div class="row mb-3 justify-content-center">
    <%= form.submit 'Create / Update Match', class: "btn btn-primary col-sm-7" %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<div class="container mt-3">
  <div class="row mb-3 justify-content-center">
    <h1 class="col-sm-7">Edit Match</h1>
  </div>
  <%= render "form", match: @match %>
</div>

app/views/matches/index.html.erb
<h1>Matches</h1>

<table>
  <tr>
    <th>Winner</th>
    <th></th>
    <th></th>
    <th>Loser</th>
    <th>Date</th>
  </tr>
  <% @matches.each do |match| %>
    <tr>
      <td><%= link_to match.winner.name, match.winner %></td>
      <td><%= match.winner_score %></td>
      <td><%= match.loser_score %></td>
      <td><%= link_to match.loser.name, match.loser %></td>
      <td><%= match.created_at.strftime('%F') %></td>
    </tr>
  <% end %>
</table>

app/views/matches/new.html.erb
<div class="container mt-3">
  <div class="row mb-3 justify-content-center">
    <h1 class="col-sm-7">Record Match</h1>
  </div>
  <%= form_with model: @match do |form| %>
    <% @match.errors.full_messages_for(:winning_player_id).each do |message| %>
      <div class="row mb-3 justify-content-center">
        <div class="alert alert-danger col-sm-7"><%= message %></div>
      </div>
    <% end %>
    <div class="row mb-3 justify-content-center">
      <%= form.label :winner, class: "col-sm-2 col-form-label" %><br>
      <div class="col-sm-5">
        <%= form.collection_select :winning_player_id, Player.order(:name),:id,:name, { include_blank: true }, { class: "form-select" } %>
      </div>
    </div>

    <div class="row mb-3 justify-content-center">
      <%= form.label :loser, class: "col-sm-2 col-form-label" %><br>
      <div class="col-sm-5">
        <%= form.collection_select :losing_player_id, Player.order(:name),:id,:name, { include_blank: true }, { class: "form-select" } %>
      </div>
    </div>

    <div class="row mb-3 justify-content-center">
      <%= form.label :winner_score, class: "col-sm-2 col-form-label" %><br>
      <div class="col-sm-5">
        <%= form.number_field :winner_score, class: "form-control" %>
      </div>
    </div>

    <div class="row mb-3 justify-content-center">
      <%= form.label :loser_score, class: "col-sm-2 col-form-label" %><br>
      <div class="col-sm-5">
        <%= form.number_field :loser_score, class: "form-control" %>
      </div>
    </div>

    <div class="row mb-3 justify-content-center">
      <%= form.submit 'Create Match', class: "btn btn-primary col-sm-7" %>
    </div>
  <% end %>
</div>

app/views/players/_form.html.erb
<%= form_with model: @player do |form| %>
  <% @player.errors.full_messages.each do |message| %>
    <div class="row mb-3 justify-content-center">
      <div class="alert alert-danger col-sm-7"><%= message %></div>
    </div>
  <% end %>
  <div class="row mb-3 justify-content-center">
    <%= form.label :player_name, class: "col-sm-2 col-form-label" %><br>
    <div class="col-sm-5">
      <%= form.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="row mb-3 justify-content-center">
    <%= form.label :players_favorite_pokemon, class: "col-sm-2 col-form-label" %><br>
    <div class="col-sm-5">
      <%= form.text_field :favorite_pokemon, class: "form-control" %>
    </div>
  </div>

  <div class="row mb-3 justify-content-center">
    <%= form.submit 'Create / Update Player', class: "btn btn-primary col-sm-7" %>
  </div>
<% end %>

app/views/players/edit.html.erb
<div class="container mt-3">
  <div class="row mb-3 justify-content-center">
    <h1 class="col-sm-7">Edit Player</h1>
  </div>
  <%= render "form", player: @player %>
</div>

app/views/players/generate_matches.html.erb
<%= form_with url: { action: :matches_to_play } do |form| %>

  <% @players.each do |player| %>
    <div class="form-check">
      <%= form.label player.name, class: "form-check-label" %>
      <%= form.check_box "player[selected][#{player.name}]", class: "form-check-input" %>
    </div>
  <% end %>

  <%= form.submit 'Create Matches', class: "btn btn-primary col-sm-7" %>
<% end %>

app/views/players/index.html.erb
<div class="text-center mb-3">
  <%= image_tag("pokemon_league.png", height: 197, width: 173) %>
</div>

<table class="table">
  <tr>
    <th>Player</th>
    <th>Match Wins</th>
    <th>Match Losses</th>
    <th>Game Wins</th>
    <th>Game Losses</th>
  </tr>
  <% @sorted_players.each do |player| %>
    <tr>
      <td>
        <img src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/<%= player.favorite_pokemon_id %>.png" class="float-start" alt="Pokemans" width="32" height="32">
        <%= link_to player.name, player, class: "list-group-item" %>
      </td>
      <td><%= player.wins_and_losses[:matches_won] %></td>
      <td><%= player.wins_and_losses[:matches_lost] %></td>
      <td><%= player.wins_and_losses[:games_won] %></td>
      <td><%= player.wins_and_losses[:games_lost] %></td>
    </tr>
  <% end %>
</table>

app/views/players/matches_to_play.html.erb
<div class="card w-20">
  <ul class="list-group list-group-flush">
    <% @pairings.each do |p1, p2| %>
      <li class="list-group-item">
        <div class="row">
          <div class="col-5 text-start">
            <%= p1.name %>
          </div>
          <div class="col-2 text-center">
            vs
          </div>
          <div class="col-5 text-end">
            <%= p2 == 'Bye' ? p2 : p2.name %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/players/new.html.erb
<div class="container mt-3">
  <div class="row mb-3 justify-content-center">
    <h1 class="col-sm-7">New Player</h1>
  </div>
  <%= render "form", player: @player %>
</div>

app/views/players/show.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="card border-success mb-3 w-20">
      <div class="card-header">
        <div class="row text-center">
          <div class="col-10 my-auto">
            <h5 class="mb-1 mt-1 float-beginning"><%= @player.name %></h5>
          </div>
          <div class="col-2 mobile-img">
            <img src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/<%= @player.favorite_pokemon_id %>.png" class="float-end" alt="Pokemans" width="96" height="96">
          </div>
        </div>
      </div>
      <div class="card-body">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <div class="row mb-1">
              <div class="col-10 my-auto">
                <div class="text-start"> Match Wins: </div>
              </div>
              <div class="col-2 my-auto">
                <div class="text-end"><%= @player.wins_and_losses[:matches_won] %></div>
              </div>
            </div>
          </li>
          <li class="list-group-item">
            <div class="row mb-1">
              <div class="col-10 my-auto">
                <div class="text-start"> Match Losses: </div>
              </div>
              <div class="col-2 my-auto">
                <div class="text-end"><%= @player.wins_and_losses[:matches_lost] %></div>
              </div>
            </div>
          </li>
          <li class="list-group-item">
            <div class="row mb-1">
              <div class="col-10 my-auto">
                <div class="text-start"> Game Wins: </div>
              </div>
              <div class="col-2 my-auto">
                <div class="text-end"><%= @player.wins_and_losses[:games_won] %></div>
              </div>
            </div>
          </li>
          <li class="list-group-item">
            <div class="row mb-1">
              <div class="col-10 my-auto">
                <div class="text-start"> Game losses: </div>
              </div>
              <div class="col-2 my-auto">
                <div class="text-end"><%= @player.wins_and_losses[:games_lost] %></div>
              </div>
            </div>
          </li>
        </ul>
      </div>
      <div class="card-footer text-muted">
        <%= link_to "Edit", edit_player_path(@player), class: "btn btn-primary" %>
      </div>
    </div>
  </div>
  <div class="col-md-8">
    <div>
      <table class="table">
        <tr>
          <th style="width: 10%">Winner</th>
          <th style="width: 10%"></th>
          <th></th>
          <th style="width: 10%"></th>
          <th style="width: 10%">Loser</th>
          <th style="width: 50%">Date</th>
          <th style="width: 10%"></th>
        </tr>
        <% @player.matches.each do |match| %>
          <tr>
            <td><%= link_to match.winner.name, match.winner, class: "list-group-item" %></td>
            <td class="text-end"><%= match.winner_score %></td>
            <td>-</td>
            <td><%= match.loser_score %></td>
            <td><%= link_to match.loser.name, match.loser, class: "list-group-item" %></td>
            <td><%= match.created_at.strftime('%F') %></td>
            <td> <%= link_to "Edit", edit_match_path(match), class: "btn btn-primary" %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>

</div>